DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CONTRACTS;
DROP TABLE IF EXISTS ECONOMIC_SECTORS;

CREATE TABLE ECONOMIC_SECTORS (
                        ID INT NOT NULL AUTO_INCREMENT
     , CODE VARCHAR(1) NOT NULL
     , DESCRIPTION VARCHAR(200) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
       ID INT NOT NULL AUTO_INCREMENT
     , CODE VARCHAR(12) NOT NULL
     , DESCRIPTION VARCHAR(250) NOT NULL
     , ECONOMIC_CODE VARCHAR(1) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE CONTRACTS (
                       ID INT NOT NULL AUTO_INCREMENT
    , PRODUCT_CODE VARCHAR(12) NOT NULL
    , REGION_CODE VARCHAR(3) NOT NULL
    , SIGN_DATE DATE NOT NULL
    , AMOUNT LONG NOT NULL
    , CURRENCY_CODE VARCHAR(10) NOT NULL
    , PRIMARY KEY (ID)
);



